name: playback_caf_dart
description: CAF implementation for ChromiTube
# version: 1.0.0
#homepage: https://www.interfaceag.de
#author: Aron Metzig <aron.metzig@interface-ag.de>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  test: ^1.9.4
  optional: ^4.0.1
  dcache: ^0.3.0
  playback_interop:
    path: ../playback_interop

dev_dependencies:
  build_runner: ^1.6.0
  build_test: ^0.10.11
  build_web_compilers: ^2.7.2
  pedantic: ^1.8.0
  js: ^0.6.1+1
  http: ^0.12.0+2
  mockito: ^4.1.1
