name: playback_caf_dart
description: CAF implementation for ChromiTube
# version: 1.0.0
#homepage: https://www.interfaceag.de
#author: Aron Metzig <aron.metzig@interface-ag.de>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  test: ^1.14.2
  optional: ^4.1.0
  dcache: ^0.3.0
  playback_interop:
    path: ../playback_interop

dev_dependencies:
  build_runner: ^1.8.1
  build_test: ^1.0.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
  js: ^0.6.1+1
  http: ^0.12.0+4
  mockito: ^4.1.1
