name: playback_caf_dart
description: CAF implementation for ChromiTube
# version: 1.0.0
#homepage: https://www.interfaceag.de
#author: Aron Metzig <aron.metzig@interface-ag.de>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  test: ^1.16.3
  dcache: ^0.3.0
  optional: ^5.0.0+1
  playback_interop:
    path: ../playback_interop

dev_dependencies:
  build_runner: ^1.11.1
  build_test: ^1.3.6
  build_web_compilers: ^2.16.3
  pedantic: ^1.10.0
  js: ^0.6.3
  http: ^0.13.0
  mockito: ^4.1.3
