name: playback_interop
description: Shared logic between caf and flutter world.
# version: 1.0.0
# homepage: https://www.example.com
# author: Aron Metzig <aron.metzig@fau.de>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: ^1.11.5
  json_serializable: ^4.0.1
  test: ^1.16.3
