name: playback_interop
description: Shared logic between caf and flutter world.
# version: 1.0.0
# homepage: https://www.example.com
# author: Aron Metzig <aron.metzig@fau.de>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1
  fixnum: ^0.10.11

dev_dependencies:
  build_runner: ^1.6.0
  test: ^1.6.0
  json_serializable: ^3.2.5
