// Mocks generated by Mockito 5.0.16 from annotations
// in chrome_tube/test/playback_manager_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:chrome_tube/playback/playback.dart' as _i3;
import 'package:chrome_tube/playback/src/ipc/cast_playback_context.dart' as _i4;
import 'package:chrome_tube/ui/common/state.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:playback_interop/playback_interop.dart' as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [UIListener].
///
/// See the documentation for Mockito's code generation for more information.
class MockUIListener extends _i1.Mock implements _i2.UIListener {
  MockUIListener() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onEvent(_i3.PlaybackUIEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CastPlaybackContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockCastPlaybackContext extends _i1.Mock
    implements _i4.CastPlaybackContext {
  MockCastPlaybackContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> send(_i6.CastMessage<dynamic>? message) =>
      (super.noSuchMethod(Invocation.method(#send, [message]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<void> end() => (super.noSuchMethod(Invocation.method(#end, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i5.Future<void>);
  @override
  String toString() => super.toString();
}
