name: chrome_tube
description: Spotify Chromecast Party
publish_to: none
version: 1.3.1+21

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cast_button:
    path: forked/flutter_cast_button
  playback_core:
    path: ../core
  reorderables:
    path: forked/reorderables

  async: ^2.8.2
  cached_network_image: ^3.1.0
  cupertino_icons: ^1.0.3
  dcache: ^0.4.0
  edit_distance: ^0.5.0-nullsafety.0
  fading_edge_scrollview: ^2.0.1
  flutter_cache_manager: ^3.1.2
  flutter_slidable: ^0.6.0
  http: ^0.13.4
  json_annotation: ^4.3.0
  palette_generator: ^0.3.2
  path_provider: ^2.0.5
  sentry_flutter: ^6.0.1
  shared_preferences: ^2.0.8
  tuple: ^2.0.0
  webview_flutter: ^2.1.2

dev_dependencies:
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  mockito: ^5.0.16

flutter_icons:
  image_path: "assets/image/icon.png"
  android: false
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/transparent.png
    - i18n/de.json
    - i18n/en.json
