name: playback_core
description: Shared logic between caf and flutter world.
# version: 1.0.0
# homepage: https://www.example.com
# author: Aron Metzig <aron.metzig@fau.de>

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  test: ^1.19.2
